spring:
  datasource:
    url: jdbc:h2:file:D:/study/springbook/data;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enable: true
      path: /springbook

  thymeleaf:
    mode: HTML

  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

server:
  port: 5050

#logging:
#  level:
#    org.hibernate.SQL: debug # logger
#    org.hibernate.type: trace
#    org.springframework: INFO
#    org.springframework.web: DEBUG